# Generated by Django 2.0.5 on 2018-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blood_sugar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='carbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
