# Generated by Django 2.0.5 on 2018-05-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180528_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
