# Generated by Django 2.0.5 on 2018-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180528_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blood_sugar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='carbs',
            field=models.IntegerField(null=True),
        ),
    ]
