# Generated by Django 2.0.5 on 2018-05-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180528_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blood_sugar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
    ]
