# Generated by Django 2.0.5 on 2018-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180529_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blood_sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='carbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
