# Generated by Django 2.0.5 on 2018-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_entry_insulin'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='insulin_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
