# Generated by Django 2.0.5 on 2018-06-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_entry_insulin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='insulin_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
