# Generated by Django 2.0.5 on 2018-06-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180610_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='event_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Dexcom', 'Auto')], default='Manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='insulin_type',
            field=models.CharField(choices=[('Tresiba', 'Basal'), ('Fiasp', 'Bolus')], default='Fiasp', max_length=10),
        ),
    ]
