# Generated by Django 2.0.5 on 2018-06-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20180610_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='insulin_type',
            field=models.CharField(choices=[('Tresiba', 'Basal'), ('Fiasp', 'Bolus')], default='Fiasp', max_length=10),
        ),
    ]
